### PR TITLE
Fix feature check macros for POSIX realpath

### LINKED ISSUE #4301: Cannot compile library due to _BSD_SOURCE wrong usage
Hello, 
I'm not a C expert, but I'm having problem compiling when I include [open62541](https://github.com/open62541/open62541/tree/master) lib (the amalgamated single file)

The error I have is 
```
/mnt/c/Program Files/Dassault Systemes/B426_Cloud/win_b64/resources/Dymola/source/ModelicaInternal.c: In function ‘ModelicaInternal_fullPathName’:
/mnt/c/Program Files/Dassault Systemes/B426_Cloud/win_b64/resources/Dymola/source/ModelicaInternal.c:609:37: error: operator '||' has no left operand
```
line 609 looks like that in my dymola install :
`#if defined(_WIN32) || (_BSD_SOURCE || _XOPEN_SOURCE >= 500 || _XOPEN_SOURCE && _XOPEN_SOURCE_EXTENDED || (_POSIX_VERSION >= 200112L))
`
The concerned line in the actual lib seems this one : https://github.com/modelica/ModelicaStandardLibrary/blob/bc5c458731def2ad5b128feb1b7e9a563b031a6a/Modelica/Resources/C-Sources/ModelicaInternal.c#L687

I think this occur because the _BSD_SOURCE define is empty because of this line in my lib :
https://github.com/open62541/open62541/blob/6115a47125d7e6ccd77488b8572807171adb0602/tools/ua-tool/ua.c#L18

open62541 seems legit to define _BSD_SOURCE empty 
see https://ftp.gnu.org/old-gnu/Manuals/glibc-2.2.3/html_node/libc_13.html

I would suggest replacing _BSD_SOURCE by defined(_BSD_SOURCE) in ModelicaInternal.c
I can open a MR is it seem the right fix 

Note that there is three occurence of _BSD_SOURCE to fix

### PR DESCRIPTION
**Pull request by beutlich**
Resolves #4301.

This is PR for master that hopefully can get back-ported to main/4.1.0 after merge.

### CODE REVIEW

File: Modelica/Resources/C-Sources/ModelicaInternal.c [hunk 1]
```diff
@@ -671,6 +671,13 @@ int ModelicaInternal_getNumberOfFiles(_In_z_ const char* directory) {
 
 _Ret_z_ const char* ModelicaInternal_fullPathName(_In_z_ const char* name) {
     /* Get full path name of file or directory */
+#undef MODELICA_INTERNAL_HAVE_POSIX_REALPATH
+#if defined(_BSD_SOURCE) || \
+    (defined(_XOPEN_SOURCE) && _XOPEN_SOURCE >= 500) || \
+    (defined(_XOPEN_SOURCE) && defined(_XOPEN_SOURCE_EXTENDED)) || \
+    _POSIX_VERSION >= 200112L
```
Comment (beutlich) [inline Modelica/Resources/C-Sources/ModelicaInternal.c:678]:
```suggestion
    (defined(_POSIX_VERSION) && _POSIX_VERSION >= 200112L)
```
?

Comment (HansOlsson) [reply Modelica/Resources/C-Sources/ModelicaInternal.c:678]: Not needed. If _POSIX_VERSION is undefined it is treated as 0 by the pre-processor.
See https://stackoverflow.com/questions/65745333/c-preprocessor-what-is-the-motivation-behind-treating-undefined-macro-as-0 for the reason behind it.

Comment (HansOlsson) [reply Modelica/Resources/C-Sources/ModelicaInternal.c:678]: And if someone defines it to a non-numeric value it doesn't help.

Comment (beutlich) [reply Modelica/Resources/C-Sources/ModelicaInternal.c:678]: Thanks. Ok as is.

**Comment by TeoGoddet** [comment]
@beutlich on my system and with the lib creating the problem (open62541), switching to defined(_BSD_SOURCE) did not fix the problem. 
The problem was then that realpath was not availlable, which may be not normal and due to another error in another lib

**Comment by beutlich** [comment]
@TeoGoddet Can you please find out why realpath is not available when you expected it to be available?

**Comment by TeoGoddet** [comment]
@beutlich I don't think that realpath should be available (dymola windows with visual studio 22 compiler) 

I will try to understand if Open62541 is doing wrong or not with the BSD_SOURCE

https://github.com/open62541/open62541/blob/3f381ea37a8e2c0e352a0e05f49859627f753ac1/tools/ua-tool/ua.c#L18

**Comment by beutlich** [comment]
@TeoGoddet OK, waiting for your feedback then.

**Comment by beutlich** [comment]
@TeoGoddet I also do not understand why would you want to build ua.c (executable) togetheer with ModelicaInternal.c. 😕

**Comment by TeoGoddet** [comment]
@beutlich sorry I gave the wrong file, the problematic one is : https://github.com/open62541/open62541/blob/88dbcb6d644aaf3c38d2a1af9fc9cc2755c24c42/arch/win32/ua_architecture.h#L133
They may be wrong defining _BSD_SOURCE without defining all the expected function, what do you think ?

**Comment by beutlich** [comment]
> what do you think ?

That header file is 5 years old and not part of current open62541 code. Still being confused.

**Comment by TeoGoddet** [comment]
@beutlich It end up in the single file version of the lib for some reason
I tested removing it and it seems to work still
I create an issue on their side about this

On this side I think that this PR is needed to ensure proper handling of `-D_BSD_SOURCE` that is quite common

**Comment by beutlich** [comment]
@TeoGoddet Could you please share a minimal Modelica model and workflow (in a separate repo) that demonstrates your observations? Thanks!

**Comment by casella** [comment]
@sjoelund, @adrpo, @AnHeuermann can you please review this and/or comment? I think this is OK but I'm not much into this kind of low-level C programming.

**Comment by AnHeuermann** [comment]
Sorry, I don't know how this POSIX stuff is supposed to work, so I can't give a review.

**Comment by casella** [comment]
Maybe @fedetft could help with that? He for sure knows a thing or two about POSIX 😄

**Review by casella — APPROVED** [review]
